---
title: "p8105_hw2_ym2813"
author: "Anna Ma"
date: "10/4/2021"
output: github_document
---

```{r}
library(tidyverse)
library(readxl)
```

## Problem 1

Read and clean the Mr.Trash Wheel sheet

```{r}
trash_wheel_df = 
  read_excel("data_hw2/Trash-Wheel-Collection-Totals-7-2021-sept.xlsx", 
             sheet = 1, col_names = TRUE, range = "A2:N408") %>% 
  janitor::clean_names() %>%  #clean the variable names
  drop_na(dumpster) %>% #omitting rows without dumpster-specific data
  rename(weight = weight_tons,volume = volume_cubic_yards) %>% #reasonable variable name 
  mutate(sports_balls = round(sports_balls,0)) #round sports_ball to integer
```

Read and clean precipitation data for 2018 

```{r}
precipitation_2018_df = 
  read_excel("data_hw2/Trash-Wheel-Collection-Totals-7-2021-sept.xlsx", 
             sheet = 8, range = "A2:B15") %>% 
  janitor::clean_names() %>% 
  drop_na() %>% 
  mutate(year = "2018") %>% 
  select(year,month,total)
```

Read and clean precipitation data for 2019

```{r}
precipitation_2019_df = 
  read_excel("data_hw2/Trash-Wheel-Collection-Totals-7-2021-sept.xlsx", 
             sheet = 7, range = "A2:B15") %>% 
  janitor::clean_names() %>% 
  drop_na() %>% 
  mutate(year = "2019") %>% 
  select(year,month,total)
```

